Compute full Kodaira type of singular loci
Julia-meets-String-Theory/FTheoryTools.jl pull request #19
Opened 2022-12-23 01:44 UTC by apturner

Add functionality to singular_loci to compute orders of vanishing of (f, g, Delta) at each singular locus.

2022-12-23 13:58 UTC, HereAround requested changes
Thank you @apturner . It is rather cool that we can now compute the vanishing orders and thus the singularity type. That is cool!

I made a few minor suggestions on potential spelling mistakes (but you are the expert in that regard, so feel free to overrule them).

Two comments:
1. I find it cool that `bibtool` allows to standardized the bibtex entries. This would also detect doubled entries, or "almost" doubled entries (e.g. same author and title, different bibkeys and one of them knows about the journal the article was published in). Cf. https://julia-meets-string-theory.github.io/FTheoryTools.jl/dev/developer/. Your reference is not in "the" standard format (that was chosen for OSCAR). I added the corresponding suggestion above. Imho it would be great if this could be changed.
2. I understand that people had tons of arguments and even more strong opinion on whether or not there should be commits of the form "merged master into...". So consider the following optional and purely my personal preference. Namely, I prefer to not have such merge commits. Rather, I would suggest to use `rebase` (possibly in combination with `cherry-pick`). Here, I would thus integrate 9d662b6fd8373d801d6af396aaccbefbc7dc2630 into f3fc794a0b3b7fbaec00a6f60c77c88fa1d1af71. But to emphasize again, this is optional.

2022-12-23 13:58 UTC, HereAround commented on src/WeierstrassModels/attributes.jl
> +computing the singular of the discriminant of this Weierstrass model.
```suggestion
computing the singular loci of the discriminant of this Weierstrass model.
```

2022-12-23 13:58 UTC, HereAround commented on src/TateModels/attributes.jl
> +And implicitly, in case we work over a non-fully specified base. This has the
```suggestion
and implicitly, in case we work over a non-fully specified base. This has the
```

2022-12-23 13:58 UTC, HereAround commented on src/WeierstrassModels/attributes.jl
> +And implicitly, in case we work over a non-fully specified base. This has the
```suggestion
and implicitly, in case we work over a non-fully specified base. This has the
```

2022-12-23 13:58 UTC, HereAround commented on docs/references.bib
> +
```suggestion
@Article{KMSS11,
  author        = "Katz, Sheldon and Morrison, David R. and Schafer-Nameki,
                  Sakura and Sully, James",
  title         = "{Tate's algorithm and F-theory}",
  journal       = "JHEP",
  volume        = "08",
  pages         = "094",
  year          = "2011",
  doi           = "10.1007/JHEP08(2011)094",
  eprint        = "1106.3854",
  archiveprefix = "arXiv",
  primaryclass  = "hep-th",
  reportnumber  = "UCSB-MATH-2011-09, IPMU11-0107, NSF-KITP-11-110,
                  KCL-MTH-11-13"
}
```

This is the entry in the standard format (of Oscar), as is being invoked by `bibtool` (cf. https://julia-meets-string-theory.github.io/FTheoryTools.jl/dev/developer/).

2022-12-24 04:25 UTC, apturner commented
Thank you @HereAround for the comments. They should all be addressed in e57209a.

2022-12-24 07:31 UTC, HereAround approved these changes
Thank you @apturner. Looks great!

2022-12-24 07:31 UTC, merged